### ISSUE TITLE
TypeError with etree

### ISSUE THREAD

**Issue by sectide** [exitnode/esm2markdown#1]
New to python. Running esm2markdown on debian 9.4 and receiving the below TypeError.

debian:~$ python3 esm2markdown.py ESM_RuleExport_6-25-18.xml rules.mk
Traceback (most recent call last):
  File "esm2markdown.py", line 355, in <module>
    parseXML(sys.argv[1])
  File "esm2markdown.py", line 232, in parseXML
    root = sortXML(xmlfile)
  File "esm2markdown.py", line 98, in sortXML
    data.sort()
TypeError: '<' not supported between instances of 'lxml.etree._Element' and 'lxml.etree._Element'

**Comment by exitnode** [comment]
Looks like some dependencies are missing. Please try installing them with "sudo apt-get install python3-lxml python3-networkxi python3-pydot"

**Comment by sectide** [comment]
Interesting. I installed all at the initial setup of my system per the requirements in README.md. After trying again I get:

python3-lxml is already the newest version (4.2.1-1).
python3-networkx is already the newest version (2.1-1).
python3-pydot is already the newest version (1.2.4-1).

**Comment by exitnode** [comment]
You are right, I misread your initial question and the included output. I'll check and will come back to you

**Comment by exitnode** [comment]
Does it work with my sample xml file demo/demo.xml?
If yes and if your xml doesn't contain any secrets it would be helpful if I could have it in order to find out whats going on.

**Comment by sectide** [comment]
The demo.xml works. So likely some nuance with my xml.  No secrets in my xml specifically, but I'd prefer not post it here. Do you have a private repository that I could post it to?

**Comment by exitnode** [comment]
Sadly not but you can send it to me via email to clemens@sdf.org

**Comment by exitnode** [comment]
Thanks for providing me with the XML file. It seems that the sort function requires the <message> to be unique. In your XML some message tags are not unique. I'll send you further information via mail and will look into how I can fix this problem in the code. I recommend you to rename the rule message texts in order to generate the markdown file.

**Comment by exitnode** [comment]
The script has now been updated to check the input file for duplicate rule names. It will print out the affected rules and abort the operation.
